name: "MySpace"
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '31 5 * * 5'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: First interaction
      uses: actions/first-interaction@v1.1.0
      with:
        # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
        repo-token: secrets.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
        # Comment to post on an individual's first issue
        issue-message: "your issue was set" # optional
        # Comment to post on an individual's first pull request
        pr-message: "your pull-request was satisfied all requirements" # optional 
